config/routes.rb
Rails.application.routes.draw do
  resources :search_seggestions
  get 'reviews/new'

  get 'reviews/create'

  get 'order_products/create'

  get 'orders/new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'products#index'
  resources :products do
    member do
      post 'add_to_cart'
    end
  end
  resources :order_products, only: [:create, :destroy] do
    member do
      post 'add_same_to_cart'
      post 'remove_same_from_cart'
    end
  end

  resources :carts, only: [:show, :destroy]
  resources :orders, only: [:new, :create, :destroy]
  resources :reviews, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ApplicationRecord
  has_many :order_products, dependent: :destroy

  def add_product(product_id)
    current_item = order_products.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = order_products.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    order_products.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_cart
  end

  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    session[:count_of_products] = nil
    redirect_to root_url, notice: 'Cart is empty'
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<% if @cart.order_products.empty? %>
    <h3>Your Cart is empty</h3>
<% else %>
  <ul>
    <% @cart.order_products.each do |order_product| %>
      <li id="order_product_item_<%= order_product.id %>">
        <%= link_to '',
                    order_product,
                    class: 'glyphicon glyphicon-trash',
                    method: :delete, confirm: 'Are you sure?' %>
        <%= link_to order_product.product.name,
                    product_path(order_product.product) %>:
        <span id="item_total_price_<%= order_product.id %>"><%= number_to_currency(order_product.total_price,
                               unit: 'грн.',
                               format: '%n %u',
                               separator: ',') %></span>

        - <span id="quantity_order_product_<%= order_product.id %>"><%= order_product.quantity %></span>

        <%= link_to '', add_same_to_cart_order_product_path(order_product), class: 'glyphicon glyphicon-plus', remote: true, method: :post %> /
        <%= link_to '', remove_same_from_cart_order_product_path(order_product), class: 'glyphicon glyphicon-minus', remote: true,  method: :post %>

      </li>
    <% end %>
  </ul>
  Total price is <span id="cart_total_price"><%= number_to_currency(@cart.total_price,
                                        unit: 'грн.',
                                        format: '%n %u',
                                        separator: ',') %></span><%= link_to 'Do Order', new_order_path, class: 'btn btn-warning' %>
  <%= button_to 'Empty cart', @cart, method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger' %>

<% end %>