config/routes.rb
Rails.application.routes.draw do
  resources :search_seggestions
  get 'reviews/new'

  get 'reviews/create'

  get 'order_products/create'

  get 'orders/new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'products#index'
  resources :products do
    member do
      post 'add_to_cart'
    end
  end
  resources :order_products, only: [:create, :destroy] do
    member do
      post 'add_same_to_cart'
      post 'remove_same_from_cart'
    end
  end

  resources :carts, only: [:show, :destroy]
  resources :orders, only: [:new, :create, :destroy]
  resources :reviews, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  price       :decimal(8, 2)    default(0.0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  price_old   :decimal(8, 2)    default(0.0)
#  immage      :string
#

class Product < ApplicationRecord
  has_many :related_products
  has_many :reviews
  has_many :feature_values
  has_many :features, through: :feature_values
  has_many :order_products
  has_many :orders, through: :order_products
  belongs_to :category

  scope :includes_reviews_published_true, -> { includes(:reviews).where(reviews: { published: true }) }

  validates :name, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 3 }

  before_destroy :ensure_not_referenced_by_any_order_product

  private

  def ensure_not_referenced_by_any_order_product
    if order_products.empty?
      true
    else
      errors.add(:base, 'In order_products now')
      false
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :last_added_products, except: :add_to_cart
  def index
    @products =
      if params[:category]
        categories = Category.find(params[:category]).subtree_ids
        Product.includes_reviews_published_true.where(category: categories)
      elsif params[:search]
        Product.includes_reviews_published_true.where("name ILIKE ?", "%#{params[:search]}%")
      else
        Product.includes_reviews_published_true.all
      end.paginate(page: params[:page], per_page: 9)
    @product_for_carusel = Product.all.sample(5)
    render :index
  end

  def show
    @review = Review.new
    @product = Product.find(params[:id])
  end

  def add_to_cart
    product_id = params[:id]
    if cookies[:cart].present?
      product = cookies[:cart].split(',')
      product << product_id
      cookies[:cart] = product.join(',')
    else
      cookies[:cart] = product_id
    end
    redirect_back fallback_location: { action: 'show', id: product_id }
  end

  private

  def last_added_products
    @last_added_products = Product.order(created_at: :desc).limit(3)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_karusel_html.erb
<div class="row carousel-holder">

  <div class="col-md-12">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <% @product_for_carusel.each_with_index do |product, index| %>
          <div class="item <%= 'active' if index == 0 %>">
            <%= link_to image_tag("800x300/#{product.immage}", class: 'slide-image'), product_path(product) %>
          </div>
        <% end %>
      </div>

      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true" ></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true" ></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

app/views/products/_product.html.erb
<div class="col-sm-4 col-lg-4 col-md-4">
  <div class="thumbnail">
    <%= link_to (image_tag("320x150/#{product.immage}")), product_path(product) %>
    <div class="caption">
      <h4><a href="#"><%= link_to product.name, product_path(product) %></a>
      </h4>
      <p><%= truncate(product.description, length: 25){ link_to '...Fool description', product_path(product) } %></p>
      <h4 class="pull-right"><%= number_to_currency(product.price, unit: 'грн.', format: '%n %u', separator: ',') %></h4>
    </div>
    <div class="ratings">
      <p class="pull-right"><%= pluralize(product.reviews.count, 'review') %></p>
      <p>
        <% total_rating = 0 %>
        <% product.reviews.each do |view| %>
          <% total_rating += view.rating %>
        <% end %>

        <% begin  %>
          <% average_rating = total_rating/product.reviews.count %>
        <% rescue ZeroDivisionError %>
          <% average_rating = 0 %>
        <% end %>

        <% average_rating.times do %>
            <span class="glyphicon glyphicon-star"></span>
        <% end %>
        
        <% (5-average_rating).times do %>
            <span class="glyphicon glyphicon-star-empty"></span>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/products/_review.html.erb
<hr>

<div class="row">
  <div class="col-md-12">
    <% review.rating.times do %>
      <span class="glyphicon glyphicon-star"></span>
    <% end %>
    <% (5 - review.rating).times do %>
      <span class="glyphicon glyphicon-star-empty"></span>
    <% end %>x
    <%= review.author %>
    <span class="pull-right"><%= distance_of_time_in_words_to_now review.created_at %></span>
    <p><%= review.body %></p>
  </div>
</div>

app/views/products/index.html.erb
<div class="col-md-9">
  <%= render 'products/karusel_html' %>

  <div class="row">
    <%= render @products %>
    <hr>
    <%= will_paginate @products %>
  </div>
  <div class="row">
    <hr>
    Last added productsz
    <hr>
    <% @products = @last_added_products  %>
    <%= render partial: 'products/product', collection: @products %>
  </div>
</div>

<!--&lt;!&ndash; jQuery &ndash;&gt;-->
<!--<script src="js/jquery.js"></script>-->

<!--&lt;!&ndash; Bootstrap Core JavaScript &ndash;&gt;-->
<!--<script src="js/bootstrap.min.js"></script>-->

app/views/products/show.html.erb
<div class="col-md-9">

  <div class="thumbnail">
    <%= image_tag("800x300/#{@product.immage}") %>
    <div class="caption-full">
      <h4 class="pull-right"><%= number_to_currency(@product.price, unit: 'грн.', format: '%n %u', separator: ',') %></h4>
      <h4><a href="#"><%= @product.name %></a></h4>

      <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">description</a></li>
        <li><a data-toggle="tab" href="#menu1">specifications</a></li>
      </ul>

      <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
          <h3>description</h3>
          <p><%= @product.description %></p>
        </div>

        <div id="menu1" class="tab-pane fade">
          <h3>specifications</h3>
          <p>
            <% @product.feature_values.each do |feature_value| %>
                <b><%= feature_value.feature.title %>:</b>  - <%= feature_value.title %> <br>
            <% end %>
          </p>
        </div>
      </div>

    </div>
    <span id="for_notice">
    </span>
    <div class="text-right"><%= button_to 'Add to cart', order_products_path(product_id: @product),class: "btn btn-danger", remote: true %></div>

    <br>
    <div class="ratings">
      <p class="pull-right"><%= pluralize(@product.reviews.list_of_published_only.count, 'review') %></p>
      <p>
        <% total_rating = 0 %>
        <% @product.reviews.each do |view| %>
            <% total_rating += view.rating %>
        <% end %>
        
        <% begin  %>
          <% average_rating = total_rating/@product.reviews.list_of_published_only.count %>
        <% rescue ZeroDivisionError %>
          <% average_rating = 0 %>
        <% end %>
        
        

        <% average_rating.times do %>
            <span class="glyphicon glyphicon-star"></span>
        <% end %>
        <% (5-average_rating).times do %>
            <span class="glyphicon glyphicon-star-empty"></span>
        <% end %>
        <%= pluralize(average_rating, 'star') %>
      </p>
    </div>
  </div>
  <div class="well">
    <div class="text-right">
      <%= link_to 'Leave a Review', new_review_path,class: 'btn btn-success', remote: true %>
    </div>

    <div class="new_review">
      <%= render 'reviews/form', review: @review, product: @product %>
    </div>
    <% @product.reviews.list_of_published_only.each do |review| %>
        <%= render 'products/review', review: review %>
    <% end %>

  </div>
</div>