config/routes.rb
Rails.application.routes.draw do
  resources :search_seggestions
  get 'reviews/new'

  get 'reviews/create'

  get 'order_products/create'

  get 'orders/new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'products#index'
  resources :products do
    member do
      post 'add_to_cart'
    end
  end
  resources :order_products, only: [:create, :destroy] do
    member do
      post 'add_same_to_cart'
      post 'remove_same_from_cart'
    end
  end

  resources :carts, only: [:show, :destroy]
  resources :orders, only: [:new, :create, :destroy]
  resources :reviews, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- /.container -->
<div class="container">
  <hr>
  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Adamenko 2017</p>
      </div>
    </div>
  </footer>

</div>
<!-- /.container -->

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar">sdsd</span>
        <span class="icon-bar">adasd</span>
        <span class="icon-bar">asdasd</span>
      </button>
      <%= link_to 'My Store', root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="#">About</a>
        </li>
        <li>
          <span >
            <%= link_to '', cart_path(1), class: 'glyphicon glyphicon-shopping-cart'%> <span class='count'><%= session[:count_of_products] %></span>
          </span>
        </li>
        <li>
          <%= link_to 'Admin', admin_root_path %>
        </li>
        <li>
          <%= form_tag products_path, method: :get do %>
            <%= text_field_tag :search %>
            <%= submit_tag 'Search', name: nil %>
          <% end %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <!-- Page Content -->
    <div class="container for_notice">
        <% if notice %>
          <div class="alert alert-success">
            <%= notice %>
          </div>
        <% end %>
      <div class="row">
        <div class="col-md-3">
          <div class="list-group">
            <%= nested_category(@category.arrange(order: :name)) %>
          </div>
        </div>

        <%= yield %>

      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>